<?php
 $aik =  array (
  'title' => '沐光-於-江湖导航 h.xz.cn',
  'keywords' => '沐光-於-江湖导航，综合导航网站。全网软件、影视、小说、办公、工具、源码、系统、新闻、旅游、文化、生活、资源、手机等优质网站和科技的网站',
  'description' => '一个互联网的集合网址导航,为网友提供专业的网址导航,汇集全网优质网址及资源的中文上网导航。收录分类的网址和内容，让您的网络生活更简单精彩',

  '1zi' => '等待添加',
  '2zi' => '等待添加',
  '3zi' => '等待添加',
  '4zi' => '等待添加',
  '5zi' => '等待添加',
  '6zi' => '等待添加',
  '7zi' => '等待添加',
  '8zi' => '等待添加',
  '9zi' => '等待添加',
  '10zi' => '等待添加',
  '11zi' => '等待添加',
  '12zi' => '等待添加',
  '13zi' => '等待添加',
  '14zi' => '等待添加',
  '15zi' => '等待添加',
  '16zi' => '等待添加',
  '17zi' => '等待添加',
  '18zi' => '等待添加',

  '1lianjie' => 'http://h.xz.cn',
  '2lianjie' => 'http://h.xz.cn',
  '3lianjie' => 'http://h.xz.cn',
  '4lianjie' => 'http://h.xz.cn',
  '5lianjie' => 'http://h.xz.cn',
  '6lianjie' => 'http://h.xz.cn',
  '7lianjie' => 'http://h.xz.cn',
  '8lianjie' => 'http://h.xz.cn',
  '9lianjie' => 'http://h.xz.cn',
  '10lianjie' => 'http://h.xz.cn',
  '11lianjie' => 'http://h.xz.cn',
  '12lianjie' => 'http://h.xz.cn',
  '13lianjie' => 'http://h.xz.cn',
  '14lianjie' => 'http://h.xz.cn',
  '15lianjie' => 'http://h.xz.cn',
  '16lianjie' => 'http://h.xz.cn',
  '17lianjie' => 'http://h.xz.cn',
  '18lianjie' => 'http://h.xz.cn',

  'admin_name' => 'mysitenic',
  'admin_pass' => 'wyfs9981',
  'logo_dh' => 'https://s2.loli.net/2023/08/29/ZpF4RcJv7QktS6G.png',
  
);
?>